name: warda
description: A Multi-vendor eCommerce service.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  calendar_date_picker2: ^0.5.2
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.1.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  custom_map_markers: ^0.0.2+1
  dartz: ^0.10.1
  dotted_border: ^2.0.0+1
  dropdown_button2: null
  easy_stepper: ^0.6.0
  expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_bloc: ^8.1.3
  flutter_credit_card: ^3.0.7
  # flutter_html: ^2.2.1
  flutter_inappwebview: ^5.7.1
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_share_me: ^1.4.0
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_typeahead: ^4.3.7
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  fwfh_text_style: ^2.22.8+1
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.4.0+5
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  http: ^0.13.4
  image_compression_flutter: ^1.0.2
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+6
  intl: null
  intl_phone_number_input: ^0.7.3+1
  just_the_tooltip: ^0.0.12
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.8
  phone_number: ^1.0.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pointer_interceptor: ^0.9.0+1
  pretty_http_logger: ^0.2.2
  qr_flutter: ^4.0.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.11
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^4.3.0
  ticket_widget: ^0.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
#  sliver_app_bar_builder: ^1.0.4
#  customizable_space_bar: ^0.2.0
dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - shorebird.yaml

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
    - family: Philosopher
      fonts:
        - asset: assets/font/Philosopher-Regular.ttf
          weight: 400
        - asset: assets/font/Philosopher-BoldItalic.ttf
          weight: 500
        - asset: assets/font/Philosopher-Bold.ttf
          weight: 700
        - asset: assets/font/Philosopher-Italic.ttf
          weight: 900

    - family: KaushanScript
      fonts:
        - asset: assets/font/KaushanScript-Regular.ttf
          weight: 500
